name: Build OpenWrt Config

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
      with: 
        submodules: recursive
        
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git
        sudo apt-get install -y bc lm-sensors pciutils luci-app-samba4 wsdd2 libpam ddns-scripts wget-ssl libkmod luci-proto-ipv6 liblzma libnetsnmp maccalc libcurl libtins libyaml-cpp glib2 libgpiod libtirpc pciids libaio
      shell: bash

    - name: Configure OpenWrt
      run: |
        export TERM=dumb  # Set a dummy terminal
        git clone https://github.com/coolsnowwolf/lede.git
        cd lede
        make menuconfig

    - name: Save .config file
      run: |
        # Save the generated ..config file to the repository
        cp .config $GITHUB_WORKSPACE/.config

    - name: Commit changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .config
        git commit -m "Auto-generated .config file"
        git push

    - name: Clean up
      run: |
        # Clean up after the build
        make clean
